In [5]:
prices = [10,20,30]
prices

[10, 20, 30]

In [ ]:
prices.append(40)
prices[3]

40

In [3]:
len(prices)

4

In [7]:
import pandas as pd
data = {'item':['pen','book','bag'],'price':[5,20,50],'qty':[10,3,2]}
df = pd.DataFrame(data)
df

   item  price  qty
0   pen      5   10
1  book     20    3
2   bag     50    2

In [13]:
df['price']
df['price']*df['qty']
df['revenue'] = df['price']*df['qty']
df

   item  price  qty  revenue
0   pen      5   10       50
1  book     20    3       60
2   bag     50    2      100

In [14]:
df['double_price'] = df['price']*2
df

   item  price  qty  revenue  double_price
0   pen      5   10       50            10
1  book     20    3       60            40
2   bag     50    2      100           100